version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - mongo_data:/data/db

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  # webapp:
  #   build:
  #     context: .
  #     dockerfile: WEB.Dockerfile
  #   depends_on:
  #     - mongodb
  #     - redis
  #   ports:
  #     - "5000:80"
volumes:
  mongo_data: